### ISSUE TITLE
how to INCLUDE?

### ISSUE THREAD

**Issue by G1305** [janschoepke/reveal_external#10]
I only want click to open external HTML.
example:
SLIDE#1 has two content (linked text)

after clicking CONTENT#1 loads EXTERNAL HTML#1.
P.S.  external HTML#1 is hidden inside SLIDEs - before clicking CONTENT#1

HOW DO THIS?

**Comment by janschoepke** [comment]
Hi, 
this feature is currently not implemented. All includes are being loaded at the same time (directly after init) right now. I will evaluate implementing this in a further version of this plugin.

**Comment by G1305** [comment]
IDEA (if possible) example:
we have 11 slides. I'm scrolling and see all slides from #1 to #10. (#11 is hidden)
in slide #1 is linked text of article, after clicking this loads slide #11(where full article is)
CAN we HIDE specific slides before clicking to open?
I think it's easiest way to fix issue
I'm beginner self learned webmaster (sorry for worrying)

**Comment by janschoepke** [comment]
I think this issue is strongly related to #9. Could this be a solution for you? 

Example: The external contents are only loaded when the specific slide was entered. So when on slide 11 there is external content, you could link slide 11 in slide 1, and before entering slide 11 by click, the external content is loaded. 

I am currenty working on an implementation for that.

**Comment by G1305** [comment]
I found backward move bug,
when I'm scrolling data-external-replace sections, for example:
[vertical slide 1]
slide 1,1
slide 1,2
slide 1,3

[vertical slide 2]
slide 2,1
slide 2,2
slide 2,3
backward move from 2,1 is 1,2 - not 1,3

**Comment by janschoepke** [comment]
Thanks for report. Please open another issue for this problem. I will have a look at it when I finished implementing lazy load. :)

**Comment by janschoepke** [comment]
I will have some great news for you in the next days... ;)

**Comment by G1305** [comment]
@janschoepke thank you very much for answers, GOOD LUCK! ^^

**Comment by G1305** [comment]
HELP YOU rstudio reveal template?
![image](https://user-images.githubusercontent.com/34474564/36367301-83991b80-156b-11e8-9145-d13e6cea8655.png)

seems good for making media publishing website using reveal (include reveal slides supported) with DYNAMIC PAGES

**Comment by G1305** [comment]
I found something, does it HELP YOU for implementing dynamic SLIDES inside sections?
![image](https://user-images.githubusercontent.com/34474564/36435302-bd117776-167a-11e8-90a5-293189a5b779.png)
source: https://bl.ocks.org/tonyfast/77f34f5867df98ca9418
@janschoepke

**Comment by janschoepke** [comment]
@G1305 Could you please describe why you want to use dynamically generated slides inside your presentation? It does not really make sense to me. 

With the upcoming and announced feature of lazy loading you still have to create the sections hardcoded, but the content of these sections were not loaded until the presentation switches to these slides. The advantage of this is to prevent the web-presentation to blow up and to sustain the general performance. 

Also I have to inform you that this "lazy-load"-feature has already been implemented, I am in final testing phase right now and I am sure I can release the update in the next week. Stay tuned. :)

**Comment by G1305** [comment]
COOL NEWS!  ^_^
ok, for example
in YAHOO news we can scroll and scroll (like as reveal)
after click something content, we can read full article - without click we can't never and we can scrolling again WITHOUT read full article(skip).

in reveal, full and short contents are stored on ALL SLIDES(next, back, up, down) and during scroll can't skip slides where full content is... 

there is my screen video about dynamic content
https://drive.google.com/open?id=1vP1MZvDc0UWuUBWuAnP3wyyJ-jntf9hX

![003](https://user-images.githubusercontent.com/34474564/36474482-1138aa40-1711-11e8-97d8-ac6d034deaa3.png)
