### ISSUE TITLE
Any interest in a async version?

### ISSUE THREAD

**Issue by tristansokol** [janschoepke/reveal_external#13]
Hello! 

Chrome gives me this error: 
![image](https://user-images.githubusercontent.com/867661/40813922-415e2522-650b-11e8-8a37-911172d8d539.png)

I'd be happy to rewrite the couple lines to use the async version of the request if there is interest to PR. Thanks!

**Comment by janschoepke** [comment]
Hi,
haved you tried setting the async option to true? When doing so, this warning should disappear. We implemented the default option of async to false due to possible issues with other reveal plugins.

**Comment by janschoepke** [comment]
So you need to add the following lines to your reveal.js config:
```
external: {
    async: true
}
```

**Comment by tristansokol** [comment]
Ahh, thanks!

**Comment by DenizThatMenace** [comment]
I realized that it is not enough to enable the `async` option from within the initial load of `external` like so:

```javascript
Reveal.initialize({
    dependencies: [
        ...
           // Allow loading slides from external files.
           { src: 'plugin/external/external.js', async: true, condition: function() { return !!document.querySelector( '[dat    a-external],[data-external-replace]' ); } }
        ...
        ],
        ...
```
Instead one explicitly needs to add it as you wrote above:
```javascript
Reveal.initialize({
    dependencies: [
        ...
           // Allow loading slides from external files.
           { src: 'plugin/external/external.js', condition: function() { return !!document.querySelector( '[dat    a-external],[data-external-replace]' ); } }
        ...
        ],
        external: { async: true },
        ...
```

Why is that so? Shouldn't the first solution be enough?
