### ISSUE TITLE
External/external.js location

### ISSUE THREAD

**Issue by MichaelNeas** [janschoepke/reveal_external#6]
Hey! If I try to run your example revealjs cannot find your `external/external.js` file.  Once you move it into `example` everything works.  I didn't know if you wanted duplication of external.js files or if you use `external/external.js` for something else.  Nice plugin btw 😃

**Comment by janschoepke** [comment]
Hey Michael, 
sorry for the late reply. In the newest commit I duplicated `external/external.js` to the plugin folder of `/example`. This should make the example work standalone. This issue should be fixed now. Thanks! :)
