### ISSUE TITLE
does not work for me

### ISSUE THREAD

**Issue by wayne-christian** [janschoepke/reveal_external#7]
Hi 
I added the js file in plugin/external/external.js and initialised but nothing worked, it broke my web page - Am I missing something?
{
			src: 'plugin/menu/menu.js'
		},
		{
			src: 'plugin/external/external.js',
			condition: function () {
				return !!document.querySelector('[data-external],[data-external-replace]');
			}
		}

ps i am running locally?

**Comment by janschoepke** [comment]
Hi, 
Have you already tried to start the sample project located in `/example/` of this repository?  Does this work for you? You will need to run a local web server, due to XHR requires this to prevent CORS.

**Comment by janschoepke** [comment]
Closed due to lack of communication.
